/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrFooter: typeof import('@gouvminint/vue-dsfr')['DsfrFooter']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrHighlight: typeof import('@gouvminint/vue-dsfr')['DsfrHighlight']
    DsfrInput: typeof import('@gouvminint/vue-dsfr')['DsfrInput']
    DsfrModal: typeof import('@gouvminint/vue-dsfr')['DsfrModal']
    DsfrRadioButtonSet: typeof import('@gouvminint/vue-dsfr')['DsfrRadioButtonSet']
    ModalTheme: typeof import('./components/modals/ModalTheme.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextCopyToClipboard: typeof import('./components/TextCopyToClipboard.vue')['default']
  }
}
